### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by gbaranski** [smokku/soldank#1]
Hi, I've got this error when trying to run:
```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: VfsError("Zip error: description() is deprecated; use Display")', client/src/main.rs:131:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Rustup version: 1.23.1
Rustc version: 1.51.0
Commit hash: 48b447b

OS: Linux

**Comment by smokku** [comment]
Whoa. This triggered some really ancient code.
`description()` is deprecated since 1.27.0, thus the meaningless error message.

Please check whether `client/resources/soldat.smod` is a real file (108002180 bytes) or unresolved LFS link.

**Comment by gbaranski** [comment]
![image](https://user-images.githubusercontent.com/34353640/115847225-08009a80-a423-11eb-9ce4-e0951a7759b6.png)
client/resources/soldat.smod is only few bytes in size

**Comment by smokku** [comment]
You will need to install https://git-lfs.github.com and
```
git lfs fetch
git lfs checkout
```

**Comment by smokku** [comment]
I've added LFS information to README and changed the panic message:
```
thread 'main' panicked at 'Failed to add `/soldat.smod` file to VFS. Make sure it is a proper ZIP file.: VfsError("Zip error: description() is deprecated; use Display")', client\src\main.rs:134:47
```

**Comment by gbaranski** [comment]
Nice, it works, good job.
![image](https://user-images.githubusercontent.com/34353640/115853638-af80cb80-a429-11eb-871a-bb60c7af636e.png)

**Comment by smokku** [comment]
BTW @gbaranski , you have a very strange window size. Did you modify it somehow?

**Comment by gbaranski** [comment]
> BTW @gbaranski , you have a very strange window size. Did you modify it somehow?

Yes, I can using window manager.

**Comment by smokku** [comment]
The window should not be resizable.
But I guess (at the screenshot) you have some kind of tiling window manager?

**Comment by gbaranski** [comment]
Yes, it is xmonad, here is a video how it looks like 

https://user-images.githubusercontent.com/34353640/115910823-98fc6380-a46d-11eb-86aa-3598bf3254a0.mp4
